### ISSUE TITLE
Consider supporting go-tasks/task Taskfile.yml

### ISSUE THREAD

**Issue by ccoVeille** [orangekame3/mk#12]
Good project

What about supporting ?

https://github.com/go-task/task

**Comment by orangekame3** [comment]
@ccoVeille 
Thank you for the good suggestion.
Implementation seems not to be difficult so I think I'll try to support it.

**Comment by ccoVeille** [comment]
Great. I assumed it would be easy as it seems similar to your project idea.

I'm glad you like my idea

**Comment by orangekame3** [comment]
@ccoVeille 

 Now I support Taskfile in [`v0.0.13`](https://github.com/orangekame3/mk/releases/tag/v0.0.13)

you can check with following comand:

```bash
go install github.com/orangekame3/mk@v0.0.13
```

or 

```bash
brew upgrade orangekame3/tap/mk
```

Then you can load Taskfile:

```bash
mk -t
```

→[Detail](https://github.com/orangekame3/mk)

Additionally, mk now supports loading remote (or local) files.

You can use it like this:

```bash
mk -f https://raw.githubusercontent.com/orangekame3/mk/main/Makefile
```

The above command also works with Taskfile.

Enjoy!
